spring.application.name=sistemabancario

# Driver oficial JDBC de MySQL.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# URL de conexión configurada con UTC, sin SSL y con solicitud de clave pública permitida.
spring.datasource.url=jdbc:mysql://localhost:3306/tp2_banco_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Credenciales mediante variables de entorno (con 'root' por defecto).
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# Configuración de JPA.
# Dialecto de MySQL para la generación adecuada de SQL.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Crea/actualiza las tablas automáticamente.
spring.jpa.hibernate.ddl-auto=update

# Formato y visualización de sentencias SQL en la consola de intellij.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Desactivación de Open-In-View para cuidar el rendimiento
spring.jpa.open-in-view=false