spring.application.name=sistemabancario

# Driver oficial JDBC de MySQL.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# URL de conexión apuntando a la base de datos 'sistema_bancario'
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_bancario?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Credenciales locales de MySQL
spring.datasource.username=lucia
spring.datasource.password=lucia

# Configuración de JPA.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Crea/actualiza las tablas automáticamente.
spring.jpa.hibernate.ddl-auto=update

# Formato y visualización de sentencias SQL en la consola.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Desactivación de Open-In-View para cuidar el rendimiento
spring.jpa.open-in-view=false

# Configuración de Servidor de Correo (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:tu_correo@gmail.com}
spring.mail.password=${MAIL_PASSWORD:tu_contraseña_16_letras}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true