### Variables Globales
@baseUrl = http://localhost:8080/api/v1/cuentas

### 1. Crear una Caja de Ahorro para el Cliente
POST {{baseUrl}}
Content-Type: application/json

{
  "clienteId": "{{cliente_id}}",
  "alias": "CARLOS.AHORRO.JUJUY",
  "cbu": "0110000000000000000001",
  "tipoCuenta": "CAJA_AHORRO",
  "saldoInicial": 50000.00
}

> {%
    client.global.set("cuenta_id_1", response.body.id);
    client.global.set("cbu_origen", response.body.cbu);
%}

### 2. Crear una Cuenta Corriente para el mismo Cliente
POST {{baseUrl}}
Content-Type: application/json

{
  "clienteId": "{{cliente_id}}",
  "alias": "CARLOS.CC.BANCO",
  "cbu": "0110000000000000000002",
  "tipoCuenta": "CUENTA_CORRIENTE",
  "saldoInicial": 100000.00,
  "margen": 20000.00,
  "costo": 1500.00
}

> {%
    client.global.set("cuenta_id_2", response.body.id);
    client.global.set("cbu_destino", response.body.cbu);
%}

### 3. Obtener Cuenta por ID
GET {{baseUrl}}/{{cuenta_id_1}}

### 4. Obtener Cuenta por CBU
GET {{baseUrl}}/cbu/{{cbu_origen}}

### 5. Obtener todas las cuentas del Cliente
GET {{baseUrl}}/cliente/{{cliente_id}}